In [3]:
import pandas as pd
import numpy as np

In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
arr1 + arr2

array([2, 4, 6])

In [6]:
arr1 * 10

array([10, 20, 30])

In [31]:
np.sum(arr1 * np.array([10]))

60

In [32]:
mtx1 = np.array([[1, 2], [3, 4], [5, 6]])
mtx2 = np.array([[1], [2]])
print(mtx1.shape, mtx2.shape)
result = np.dot(mtx1, mtx2)
print(result, result.shape)

(3, 2) (2, 1)
[[ 5]
 [11]
 [17]] (3, 1)


In [21]:
# Matrices are not commutative: A*B != B*A
# Matrices are associative: (A*B)*C = A*(B*C)

In [27]:
mtx = np.array([[2, 3], [4, 5]])
inverse_mtx = np.linalg.inv(mtx)
inverse_mtx

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [29]:
identity_mtx = np.dot(mtx, inverse_mtx)
identity_mtx

array([[1., 0.],
       [0., 1.]])

In [37]:
transpose_mtx = np.transpose(mtx)
transpose_mtx

array([[2, 4],
       [3, 5]])

In [38]:
np.transpose(np.array([[8], [1], [4]]))

array([[8, 1, 4]])